project:
  type: website

website:
  title: "Third Year Labs - Ising Model"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: code/ising.ipynb
        text: "minimal code"
      - href: dummy.qmd
        text: dummy

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
